### ISSUE TITLE
Getting request object using application/json content-type

### ISSUE THREAD

**Issue by eleazargan** [simple-swoole/simps#10]
I cannot seem to find out how to get the request object. Only URI parameters are included in documentation. Would be great if this type of request object is added into the documentation as well.

**Comment by sy-records** [comment]
I'll add that later.  That should do it. You try it.

```php
$request->rawContent();
```

**Comment by sy-records** [comment]
You can read Swoole's documentation first.

https://www.swoole.co.uk/docs/modules/swoole-http-request

https://www.swoole.co.uk/docs/modules/swoole-http-response

**Comment by sy-records** [comment]
Added. https://github.com/simple-swoole/docs/commit/ad0768d8494153d47324507f912d236e38f14ca2

Is that what you need? @eleazargan 
![image](https://user-images.githubusercontent.com/33931153/85371464-dd278a80-b562-11ea-93b8-64cf2b0f3ffd.png)

**Comment by eleazargan** [comment]
Awesome man! Thanks!
