### ISSUE TITLE
Super powerfull, congratulations

### ISSUE THREAD

**Issue by lpj145** [simple-swoole/simps#11]
Ah!, my mystake, i put issue like a party, but, first is for congratulations you, is a god job, i think move to rust in two years, but with this approach i can wait more time.

Have plans for ht2 protocol ? this product have a roadmap ? What is way to contribute ?

Sorry for much question, thanks for attention.

**Comment by sy-records** [comment]
Thank you for using Simps.

What is the ht2 protocol? HTTP2?

There is no detailed roadmap, there are some plans that are put here https://github.com/simple-swoole/simps/projects/1

Your contribution to Simps development is very welcome! You may contribute in the following ways:

* [Report issues and feedback](https://github.com/simple-swoole/simps/issues)
* Submit fixes, features via Pull Request
* Write/polish documentation

**Comment by lpj145** [comment]
Whats about postgres ? i see lot of tutorial, articles using mysql but no pgsql, have problem with this database ? yes ht2 is http2 protocol.
I discover today this project, in some time i want to contribute.

**Comment by sy-records** [comment]
The Swoole [library](https://github.com/swoole/library) doesn't implement Coroutine pgsql yet, you need to rely on [ext-postgresql](https://github.com/swoole/ext-postgresql) extension, but it doesn't seem to support connection pool mode.

Swoole supports the http2 protocol, just enable the configuration.

**Comment by lpj145** [comment]
what is method to deploy swoole application ? simple run server with configuration or need to use a proxy, like nignx, traefik, apache ?

**Comment by sy-records** [comment]
You can either deploy it directly or add a nginx proxy.
