### ISSUE TITLE
TCP的服务没有协议呢？

### ISSUE THREAD

**Issue by jhq0113** [simple-swoole/simps#16]
如果接入tcp server，得自已定义包协议，粘包问题用swoole的`package_body_offset`,`package_length_offset `,`package_length_type `等配置自己解决吗，最好引入一下`yar`、`grpc`等开源协议支持

**Comment by sy-records** [comment]
用到了就自己配置下，至于yar、grpc这些使用合适的composer包就可以吧

**Comment by jhq0113** [comment]
好的，多谢
