### ISSUE TITLE
can i connect websockets server?

### ISSUE THREAD

**Issue by staywithdream** [simple-swoole/simps#19]
can i connect websockets server?

**Comment by sy-records** [comment]
Yes, you can.
What problem did you encounter?

**Comment by staywithdream** [comment]
![image](https://user-images.githubusercontent.com/40335088/91727581-7bc00f80-ebd4-11ea-86d4-b3a168e8f62e.png)
when the host is start with 'wss://' it was stop at here.  how can i change the protocol?  if i remove 'wss://' the server return 400.

**Comment by sy-records** [comment]
Oh, I thought you were using websocket server. . . 
The mqtt client not support connecting to the websocket server

**Comment by staywithdream** [comment]
Ok I see. I am trying to use a data interface , the API said they need connected by wss based on mqtt. I dont know how.

BTW, I  saw your name is Chinese , Can we communicate in Chinese?

**Comment by sy-records** [comment]
Swoole的MQTT和WebSocket是两种协议，放一起应该会有问题，收不到数据。你可以自己试下，有问题可以加QQ群来找我

**Comment by staywithdream** [comment]
![image](https://user-images.githubusercontent.com/40335088/91786080-692bf180-ec39-11ea-9494-1702388e7d39.png)
只是部分Python实现的代码，但是我现在想要用PHP实现
![image](https://user-images.githubusercontent.com/40335088/91786144-8791ed00-ec39-11ea-93ee-717cb39aeacd.png)
