### ISSUE TITLE
mqtt发送QOS等于2的收到消息要自己回复服务端消息收到吗 不回复会重复收到

### ISSUE THREAD

**Issue by wuxian12** [simple-swoole/simps#23]

**Comment by wuxian12** [comment]
mqtt收到消息要自己处理后面的逻辑吗，例如消息qos是1的话，要自己按照协议通知服务器删除消息，qos是2一样吗，

**Comment by sy-records** [comment]
一样的，按照协议处理。示例只提供了qos1的。

**Comment by wuxian12** [comment]
实例中没看到qos1收到消息回复服务端删除消息的代码，

**Comment by sy-records** [comment]
https://github.com/simps/mqtt/tree/master/examples
