### ISSUE TITLE
多个数据库怎么创建连接，谢谢

### ISSUE THREAD

**Issue by wuzhi403** [simple-swoole/simps#27]
多个数据库怎么创建连接，谢谢

**Comment by sy-records** [comment]
目前仅支持单库，如果你使用的root账号，可以在代码中手动切换数据库

**Comment by wuzhi403** [comment]
在初始化model的时候传入db_config还是没有修改成功，我只能通过原生sql语句去修改数据库

**Comment by sy-records** [comment]
see https://github.com/simple-swoole/simps/issues/9
