### ISSUE TITLE
有没有想法整套数据库迁移

### ISSUE THREAD

**Issue by puzzle9** [simple-swoole/simps#31]
`laravel` 用多了 
然后用到这个 我竟然连数据库都不知道怎么建立了
所以问下有没有这个想法

**Comment by sy-records** [comment]
文档 https://simps.io/#/zh-cn/database/mysql 

实际上就是简单对 Swoole Library 里提供的连接池封装了下 https://wiki.swoole.com/#/coroutine/conn_pool?id=database
