### ISSUE TITLE
simple-swoole/skeleton doesn't support php8

### ISSUE THREAD

**Issue by vikbert** [simple-swoole/simps#34]
❯ composer create-project simple-swoole/skeleton todo-simps
Creating a "simple-swoole/skeleton" project at "./todo-simps"
Info from https://repo.packagist.org: #StandWithUkraine

In CreateProjectCommand.php line 435:

  Could not find package simple-swoole/skeleton with stability stable in a version installable using your PHP version, PHP extensions and Composer version.

**Comment by sy-records** [comment]
I tested with php8.0 and 8.1 can be installed. 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/33931153/163697688-fdc58fde-78b1-4691-b7b1-fa7144623608.png">
<img width="598" alt="image" src="https://user-images.githubusercontent.com/33931153/163697699-45b14ef4-96d3-44c8-a81b-363598458c49.png">
