### ISSUE TITLE
WebSocket配置ssl证书无效

### ISSUE THREAD

**Issue by XxSbyH** [simple-swoole/simps#37]
simps 版本1.0.5，swoole版本4.8

配置ssl证书后无效，客户端请求后直接进入onclose回调

![image](https://github.com/simple-swoole/simps/assets/46987813/e169a467-c30d-4933-84cf-091983f59abd)

**Comment by sy-records** [comment]
自签证书？需要加其他配置项。 可以使用单文件试试是不是配置问题。

ssl可以结合nginx实现。
