### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by eduardofg87** [simple-swoole/simps#5]
Can I translate the documentation to Portuguese and submit a PR?

**Comment by sy-records** [comment]
Of course, you are welcome to submit PR at any time.👍🏻

**Comment by eduardofg87** [comment]
I did it! https://github.com/simple-swoole/docs/pull/1

**Comment by sy-records** [comment]
I saw it, thank you for your contribution.

**Comment by sy-records** [comment]
👍🏻It's been merged.
