### ISSUE TITLE
  Uncaught Error: Class 'Swoole\Database\PDOPool' not found in /home/vagrant/Code/skeleton/vendor/simple-swoole/db/src/PDO.php:40

### ISSUE THREAD

**Issue by wuqinqiang** [simple-swoole/simps#8]
swoole 版本4.4.12
PHP Version => 7.2.11

运行命令:php bin/simps.php http:start

**Comment by sy-records** [comment]
文档有写哈。https://simps.io/#/zh-cn/install?id=%e9%80%9a%e8%bf%87-composer-%e5%88%9b%e5%bb%ba%e9%a1%b9%e7%9b%ae

![image](https://user-images.githubusercontent.com/33931153/84616354-563d3700-aefe-11ea-8115-fdab4f2afee7.png)

**Comment by wuqinqiang** [comment]
对不起 90%的问题都是因为没有好好看文档，我错了。
